(provide *helix-shorthands*
         get-all-commands-data)

(define *helix-shorthands*
  (hash "!" "run-shell-command"
        "bc" "buffer-close"
        "bc!" "buffer-close!"
        "bca" "buffer-close-all"
        "bca!" "buffer-close-all!"
        "bclose" "buffer-close"
        "bclose!" "buffer-close!"
        "bcloseall" "buffer-close-all"
        "bcloseall!" "buffer-close-all!"
        "bcloseother" "buffer-close-others"
        "bcloseother!" "buffer-close-others!"
        "bco" "buffer-close-others"
        "bco!" "buffer-close-others!"
        "bn" "buffer-next"
        "bnext" "buffer-next"
        "bp" "buffer-previous"
        "bprev" "buffer-previous"
        "cd" "change-current-directory"
        "char" "character-info"
        "cq" "cquit"
        "cq!" "cquit!"
        "dbg" "debug-start"
        "dbg-tcp" "debug-remote"
        "diffg" "reset-diff-change"
        "diffget" "reset-diff-change"
        "e" "open"
        "ear" "earlier"
        "edit" "open"
        "fmt" "format"
        "g" "goto"
        "get" "get-option"
        "hnew" "hsplit-new"
        "hs" "hsplit"
        "lang" "set-language"
        "lat" "later"
        "mv" "move"
        "mv!" "move!"
        "n" "new"
        "o" "open"
        "pwd" "show-directory"
        "q" "quit"
        "q!" "quit!"
        "qa" "quit-all"
        "qa!" "quit-all!"
        "r" "read"
        "rl" "reload"
        "rla" "reload-all"
        "set" "set-option"
        "sh" "run-shell-command"
        "sp" "hsplit"
        "toggle" "toggle-option"
        "ts-subtree" "tree-sitter-subtree"
        "u" "update"
        "vnew" "vsplit-new"
        "vs" "vsplit"
        "w" "write"
        "w!" "write!"
        "wa" "write-all"
        "wa!" "write-all!"
        "wbc" "write-buffer-close"
        "wbc!" "write-buffer-close!"
        "wq" "write-quit"
        "wq!" "write-quit!"
        "wqa" "write-quit-all"
        "wqa!" "write-quit-all!"
        "x" "exit"
        "x!" "exit!"
        "xa" "write-quit-all"
        "xa!" "write-quit-all!"
        "xit" "exit"
        "xit!" "exit!"
        "|" "pipe"))

(define (get-all-commands-data)
  '(
   ("!" . "Alias for :run-shell-command. Run a shell command")
   ("add_newline_above" . "Add newline above.")
   ("add_newline_below" . "Add newline below.")
   ("align_selections" . "Align selections.")
   ("align_view_bottom" . "Align view to bottom.")
   ("align_view_center" . "Align view to center.")
   ("align_view_middle" . "Align view to middle.")
   ("align_view_top" . "Align view to top.")
   ("append-output" . "Run shell command, appending output after each selection.")
   ("append_char_interactive" . "Append char interactively.")
   ("append_mode" . "Switch to append mode.")
   ("buffer-close" . "Close the current buffer.")
   ("buffer-close!" . "Close the current buffer forcefully, ignoring unsaved changes.")
   ("buffer-close-all" . "Close all buffers without quitting.")
   ("buffer-close-all!" . "Force close all buffers ignoring unsaved changes without quitting.")
   ("buffer-close-others" . "Close all buffers but the currently focused one.")
   ("buffer-close-others!" . "Force close all buffers but the currently focused one.")
   ("buffer-next" . "Goto next buffer.")
   ("buffer-previous" . "Goto previous buffer.")
   ("buffer_picker" . "Open buffer picker.")
   ("change-current-directory" . "Change the current working directory.")
   ("character-info" . "Get info about the character under the primary cursor.")
   ("clear-register" . "Clear given register. If no argument is provided, clear all registers.")
   ("clipboard-paste-after" . "Paste system clipboard after selections.")
   ("clipboard-paste-before" . "Paste system clipboard before selections.")
   ("clipboard-paste-replace" . "Replace selections with content of system clipboard.")
   ("clipboard-yank" . "Yank main selection into system clipboard.")
   ("clipboard-yank-join" . "Yank joined selections into system clipboard. A separator can be provided as first argument. Default value is newline.")
   ("code_action" . "Open code actions.")
   ("collapse_selection" . "Collapse selection.")
   ("command_mode" . "Switch to command mode.")
   ("command_palette" . "Open command palette.")
   ("commit_undo_checkpoint" . "Commit undo checkpoint.")
   ("completion" . "Open completions.")
   ("config-open" . "Open the user config.toml file.")
   ("config-open-workspace" . "Open the workspace config.toml file.")
   ("config-reload" . "Refresh user config.")
   ("cquit" . "Quit with exit code (default 1). Accepts an optional integer exit code (:cq 2).")
   ("cquit!" . "Force quit with exit code (default 1) ignoring unsaved changes. Accepts an optional integer exit code (:cq! 2).")
   ("debug-eval" . "Evaluate expression in current_selection debug context.")
   ("debug-remote" . "Connect to a debug adapter by TCP address and start a debugging session from a given template with given parameters.")
   ("debug-start" . "Start a debug session from a given template with given parameters.")
   ("decrement" . "Decrement under cursor.")
   ("delete_char_backward" . "Delete char backward.")
   ("delete_char_forward" . "Delete char forward.")
   ("delete_selection" . "Delete selection.")
   ("delete_selection_noyank" . "Delete selection without yanking.")
   ("delete_word_backward" . "Delete word backward.")
   ("delete_word_forward" . "Delete word forward.")
   ("diagnostics_picker" . "Open diagnostics picker.")
   ("echo" . "Prints the given arguments to the statusline.")
   ("encoding" . "Set encoding. Based on `https://encoding.spec.whatwg.org`.")
   ("enqueue-expression-in-engine" . "Enqueue expression in engine.")
   ("ensure_selections_forward" . "Ensure selections are forward.")
   ("exit" . "Write changes to disk if the buffer is modified and then quit. Accepts an optional path (:exit some/path.txt).")
   ("exit!" . "Force write changes to disk, creating necessary subdirectories, if the buffer is modified and then quit. Accepts an optional path (:exit! some/path.txt).")
   ("exit_select_mode" . "Exit select mode.")
   ("expand_selection" . "Expand selection.")
   ("extend_char_left" . "Extend char left.")
   ("extend_char_right" . "Extend char right.")
   ("extend_line" . "Extend line.")
   ("extend_line_above" . "Extend line above.")
   ("extend_line_below" . "Extend line below.")
   ("extend_line_down" . "Extend line down.")
   ("extend_line_up" . "Extend line up.")
   ("extend_next_char" . "Extend next char.")
   ("extend_next_long_word_end" . "Extend next long word end.")
   ("extend_next_long_word_start" . "Extend next long word start.")
   ("extend_next_sub_word_end" . "Extend next sub word end.")
   ("extend_next_sub_word_start" . "Extend next sub word start.")
   ("extend_next_word_end" . "Extend next word end.")
   ("extend_next_word_start" . "Extend next word start.")
   ("extend_parent_node_end" . "Extend parent node end.")
   ("extend_parent_node_start" . "Extend parent node start.")
   ("extend_prev_char" . "Extend prev char.")
   ("extend_prev_long_word_end" . "Extend prev long word end.")
   ("extend_prev_long_word_start" . "Extend prev long word start.")
   ("extend_prev_sub_word_end" . "Extend prev sub word end.")
   ("extend_prev_sub_word_start" . "Extend prev sub word start.")
   ("extend_prev_word_end" . "Extend prev word end.")
   ("extend_prev_word_start" . "Extend prev word start.")
   ("extend_search_next" . "Extend search next.")
   ("extend_search_prev" . "Extend search prev.")
   ("extend_till_char" . "Extend till char.")
   ("extend_till_prev_char" . "Extend till prev char.")
   ("extend_to_column" . "Extend to column.")
   ("extend_to_file_end" . "Extend to file end.")
   ("extend_to_file_start" . "Extend to file start.")
   ("extend_to_first_nonwhitespace" . "Extend to first non-whitespace.")
   ("extend_to_last_line" . "Extend to last line.")
   ("extend_to_line_bounds" . "Extend to line bounds.")
   ("extend_to_line_end" . "Extend to line end.")
   ("extend_to_line_end_newline" . "Extend to line end with newline.")
   ("extend_to_line_start" . "Extend to line start.")
   ("extend_to_word" . "Extend to word.")
   ("extend_visual_line_down" . "Extend visual line down.")
   ("extend_visual_line_up" . "Extend visual line up.")
   ("file_explorer" . "Open file explorer.")
   ("file_explorer_in_current_buffer_directory" . "Open file explorer in current buffer directory.")
   ("file_explorer_in_current_directory" . "Open file explorer in current directory.")
   ("file_picker" . "Open file picker.")
   ("file_picker_in_current_buffer_directory" . "Open file picker in current buffer directory.")
   ("file_picker_in_current_directory" . "Open file picker in current directory.")
   ("find_next_char" . "Find next char.")
   ("find_prev_char" . "Find prev char.")
   ("find_till_char" . "Find till char.")
   ("flip_selections" . "Flip selections.")
   ("format" . "Format the file using an external formatter or language server.")
   ("format_selections" . "Format selections.")
   ("get-current-column-number" . "Get current column number.")
   ("get-current-line-character" . "Get current line character.")
   ("get-current-line-number" . "Get current line number.")
   ("get-helix-cwd" . "Get Helix current working directory.")
   ("get-helix-scm-path" . "Get Helix SCM path.")
   ("get-init-scm-path" . "Get Init SCM path.")
   ("get-option" . "Get the current value of a config option.")
   ("global_search" . "Open global search.")
   ("goto" . "Goto line number.")
   ("goto-column" . "Goto column.")
   ("goto-line" . "Goto line.")
   ("goto_column" . "Goto column.")
   ("goto_declaration" . "Goto declaration.")
   ("goto_definition" . "Goto definition.")
   ("goto_file" . "Goto file.")
   ("goto_file_end" . "Goto file end.")
   ("goto_file_hsplit" . "Goto file in horizontal split.")
   ("goto_file_start" . "Goto file start.")
   ("goto_file_vsplit" . "Goto file in vertical split.")
   ("goto_first_change" . "Goto first change.")
   ("goto_first_diag" . "Goto first diagnostic.")
   ("goto_first_nonwhitespace" . "Goto first non-whitespace.")
   ("goto_implementation" . "Goto implementation.")
   ("goto_last_accessed_file" . "Goto last accessed file.")
   ("goto_last_change" . "Goto last change.")
   ("goto_last_diag" . "Goto last diagnostic.")
   ("goto_last_line" . "Goto last line.")
   ("goto_last_modification" . "Goto last modification.")
   ("goto_last_modified_file" . "Goto last modified file.")
   ("goto_line" . "Goto line.")
   ("goto_line_end" . "Goto line end.")
   ("goto_line_end_newline" . "Goto line end with newline.")
   ("goto_line_start" . "Goto line start.")
   ("goto_next_buffer" . "Goto next buffer.")
   ("goto_next_change" . "Goto next change.")
   ("goto_next_class" . "Goto next class.")
   ("goto_next_comment" . "Goto next comment.")
   ("goto_next_diag" . "Goto next diagnostic.")
   ("goto_next_entry" . "Goto next entry.")
   ("goto_next_function" . "Goto next function.")
   ("goto_next_paragraph" . "Goto next paragraph.")
   ("goto_next_parameter" . "Goto next parameter.")
   ("goto_next_tabstop" . "Goto next tabstop.")
   ("goto_next_test" . "Goto next test.")
   ("goto_next_xml_element" . "Goto next XML element.")
   ("goto_prev_change" . "Goto prev change.")
   ("goto_prev_class" . "Goto prev class.")
   ("goto_prev_comment" . "Goto prev comment.")
   ("goto_prev_diag" . "Goto prev diagnostic.")
   ("goto_prev_entry" . "Goto prev entry.")
   ("goto_prev_function" . "Goto prev function.")
   ("goto_prev_paragraph" . "Goto prev paragraph.")
   ("goto_prev_parameter" . "Goto prev parameter.")
   ("goto_prev_tabstop" . "Goto prev tabstop.")
   ("goto_prev_test" . "Goto prev test.")
   ("goto_prev_xml_element" . "Goto prev XML element.")
   ("goto_previous_buffer" . "Goto previous buffer.")
   ("goto_reference" . "Goto reference.")
   ("goto_type_definition" . "Goto type definition.")
   ("goto_window_bottom" . "Goto window bottom.")
   ("goto_window_center" . "Goto window center.")
   ("goto_window_top" . "Goto window top.")
   ("goto_word" . "Goto word.")
   ("half_page_down" . "Half page down.")
   ("half_page_up" . "Half page up.")
   ("hover" . "Open hover info.")
   ("hsplit" . "Open the file in a horizontal split.")
   ("hsplit-new" . "Open a scratch buffer in a horizontal split.")
   ("hsplit_new" . "Open a scratch buffer in a horizontal split.")
   ("increment" . "Increment under cursor.")
   ("indent" . "Indent selection.")
   ("indent-style" . "Set the indentation style for editing. ('t' for tabs or 1-16 for number of spaces.)")
   ("insert-output" . "Run shell command, inserting output before each selection.")
   ("insert_at_line_end" . "Insert at line end.")
   ("insert_at_line_start" . "Insert at line start.")
   ("insert_char" . "Insert char.")
   ("insert_char_interactive" . "Insert char interactively.")
   ("insert_mode" . "Switch to insert mode.")
   ("insert_newline" . "Insert newline.")
   ("insert_register" . "Insert register.")
   ("insert_string" . "Insert string.")
   ("insert_tab" . "Insert tab.")
   ("join_selections" . "Join selections.")
   ("join_selections_space" . "Join selections with space.")
   ("jump_backward" . "Jump backward in jump list.")
   ("jump_forward" . "Jump forward in jump list.")
   ("jump_view_down" . "Jump view down.")
   ("jump_view_left" . "Jump view left.")
   ("jump_view_right" . "Jump view right.")
   ("jump_view_up" . "Jump view up.")
   ("jumplist_picker" . "Open jump list picker.")
   ("keep_primary_selection" . "Keep primary selection.")
   ("keep_selections" . "Keep selections.")
   ("kill_to_line_end" . "Kill to line end.")
   ("kill_to_line_start" . "Kill to line start.")
   ("last_picker" . "Open last picker.")
   ("line-ending" . "Set the document's default line ending. Options: crlf, lf.")
   ("load-buffer!" . "Load current buffer.")
   ("log-open" . "Open the helix log file.")
   ("lsp-restart" . "Restarts the given language servers, or all language servers that are used by the current file if no arguments are supplied")
   ("lsp-stop" . "Stops the given language servers, or all language servers that are used by the current file if no arguments are supplied")
   ("lsp-workspace-command" . "Open workspace command picker")
   ("lsp_or_syntax_symbol_picker" . "Open LSP or syntax symbol picker.")
   ("lsp_or_syntax_workspace_symbol_picker" . "Open LSP or syntax workspace symbol picker.")
   ("make_search_word_bounded" . "Make search word bounded.")
   ("match_brackets" . "Match brackets.")
   ("merge_consecutive_selections" . "Merge consecutive selections.")
   ("merge_selections" . "Merge selections.")
   ("move" . "Move the current buffer and its corresponding file to a different path")
   ("move!" . "Move the current buffer and its corresponding file to a different path creating necessary subdirectories")
   ("new" . "Create a new scratch buffer.")
   ("no_op" . "No operation.")
   ("noop" . "Does nothing.")
   ("normal_mode" . "Switch to normal mode.")
   ("open" . "Open a file from disk into the current view.")
   ("open_above" . "Open newline above.")
   ("open_below" . "Open newline below.")
   ("page_cursor_down" . "Page cursor down.")
   ("page_cursor_half_down" . "Page cursor half down.")
   ("page_cursor_half_up" . "Page cursor half up.")
   ("page_cursor_up" . "Page cursor up.")
   ("page_down" . "Page down.")
   ("page_up" . "Page up.")
   ("paste_after" . "Paste after.")
   ("paste_before" . "Paste before.")
   ("paste_clipboard_after" . "Paste system clipboard after.")
   ("paste_clipboard_before" . "Paste system clipboard before.")
   ("paste_primary_clipboard_after" . "Paste system primary clipboard after.")
   ("paste_primary_clipboard_before" . "Paste system primary clipboard before.")
   ("pipe" . "Pipe each selection to the shell command.")
   ("pipe-to" . "Pipe each selection to the shell command, ignoring output.")
   ("primary-clipboard-paste-after" . "Paste primary clipboard after selections.")
   ("primary-clipboard-paste-before" . "Paste primary clipboard before selections.")
   ("primary-clipboard-paste-replace" . "Replace selections with content of system primary clipboard.")
   ("primary-clipboard-yank" . "Yank main selection into system primary clipboard.")
   ("primary-clipboard-yank-join" . "Yank joined selections into system primary clipboard. A separator can be provided as first argument. Default value is newline.")
   ("push-range-to-selection!" . "Push range to selection.")
   ("quit" . "Close the current view.")
   ("quit!" . "Force close the current view, ignoring unsaved changes.")
   ("quit-all" . "Close all views.")
   ("quit-all!" . "Force close all views ignoring unsaved changes.")
   ("range" . "Create range.")
   ("range->from" . "Get range from.")
   ("range->selection" . "Get range selection.")
   ("range->span" . "Get range span.")
   ("range->to" . "Get range to.")
   ("range-anchor" . "Get range anchor.")
   ("range-head" . "Get range head.")
   ("read" . "Load a file into buffer")
   ("record_macro" . "Record_macro.")
   ("redo" . "Redo last change.")
   ("redraw" . "Clear and re-render the whole UI")
   ("reflow" . "Hard-wrap the current selection of lines to a given width.")
   ("regex-selection" . "Select by regex.")
   ("reload" . "Discard changes and reload from the source file.")
   ("reload-all" . "Discard changes and reload all documents from the source files.")
   ("remove-current-selection-range!" . "Remove current selection range.")
   ("remove_primary_selection" . "Remove primary selection.")
   ("remove_selections" . "Remove selections.")
   ("rename_symbol" . "Rename symbol.")
   ("repeat_last_motion" . "Repeat last motion.")
   ("replace" . "Replace selection.")
   ("replace-selection-with" . "Replace selection with string.")
   ("replace_selections_with_clipboard" . "Replace selections with system clipboard.")
   ("replace_selections_with_primary_clipboard" . "Replace selections with system primary clipboard.")
   ("replace_with_yanked" . "Replace selection with yanked.")
   ("replay_macro" . "Replay macro.")
   ("reset-diff-change" . "Reset the diff change at the cursor position.")
   ("reverse_selection_contents" . "Reverse selection contents.")
   ("rotate_selection_contents_backward" . "Rotate selection contents backward.")
   ("rotate_selection_contents_forward" . "Rotate selection contents forward.")
   ("rotate_selections_backward" . "Rotate selections backward.")
   ("rotate_selections_first" . "Rotate selections first.")
   ("rotate_selections_forward" . "Rotate selections forward.")
   ("rotate_selections_last" . "Rotate selections last.")
   ("rotate_view" . "Rotate view.")
   ("rotate_view_reverse" . "Rotate view reverse.")
   ("rsearch" . "Reverse search.")
   ("run-shell-command" . "Run a shell command")
   ("save_selection" . "Save selection.")
   ("scroll_down" . "Scroll down.")
   ("scroll_up" . "Scroll up.")
   ("search" . "Search.")
   ("search_next" . "Search next.")
   ("search_prev" . "Search prev.")
   ("search_selection" . "Search selection.")
   ("search_selection_detect_word_boundaries" . "Search selection with word boundaries.")
   ("select_all" . "Select all.")
   ("select_all_children" . "Select all children.")
   ("select_all_siblings" . "Select all siblings.")
   ("select_line_above" . "Select line above.")
   ("select_line_below" . "Select line below.")
   ("select_mode" . "Switch to select mode.")
   ("select_next_sibling" . "Select next sibling.")
   ("select_prev_sibling" . "Select prev sibling.")
   ("select_references_to_symbol_under_cursor" . "Select references to symbol under cursor.")
   ("select_regex" . "Select by regex.")
   ("select_register" . "Select register.")
   ("select_textobject_around" . "Select textobject around.")
   ("select_textobject_inner" . "Select textobject inner.")
   ("selection->primary-index" . "Get primary index of selection.")
   ("selection->primary-range" . "Get primary range of selection.")
   ("selection->ranges" . "Get ranges of selection.")
   ("set-current-selection-object!" . "Set current selection object.")
   ("set-current-selection-primary-index!" . "Set current selection primary index.")
   ("set-language" . "Set the language of current buffer (show current language if no value specified).")
   ("set-option" . "Set a config option at runtime.\nFor example to disable smart case search, use `:set search.smart-case false`.")
   ("set-register" . "Set contents of the given register.")
   ("shell_append_output" . "Shell append output.")
   ("shell_insert_output" . "Shell insert output.")
   ("shell_keep_pipe" . "Shell keep pipe.")
   ("shell_pipe" . "Shell pipe each selection.")
   ("shell_pipe_to" . "Shell pipe to command.")
   ("show-clipboard-provider" . "Show clipboard provider name in status bar.")
   ("show-directory" . "Show the current working directory.")
   ("shrink_selection" . "Shrink selection.")
   ("shrink_to_line_bounds" . "Shrink to line bounds.")
   ("signature_help" . "Open signature help.")
   ("smart_tab" . "Smart tab.")
   ("sort" . "Sort ranges in selection.")
   ("split_selection" . "Split selection.")
   ("split_selection_on_newline" . "Split selection on newline.")
   ("surround_add" . "Add surrounding.")
   ("surround_delete" . "Delete surrounding.")
   ("surround_replace" . "Replace surrounding.")
   ("suspend" . "Suspend Helix.")
   ("swap_view_down" . "Swap view down.")
   ("swap_view_left" . "Swap view left.")
   ("swap_view_right" . "Swap view right.")
   ("swap_view_up" . "Swap view up.")
   ("switch_case" . "Switch case.")
   ("switch_to_lowercase" . "Switch to lowercase.")
   ("switch_to_uppercase" . "Switch to uppercase.")
   ("symbol_picker" . "Open symbol picker.")
   ("syntax_symbol_picker" . "Open syntax symbol picker.")
   ("syntax_workspace_symbol_picker" . "Open syntax workspace symbol picker.")
   ("theme" . "Change the editor theme (show current theme if no name specified).")
   ("till_prev_char" . "Till prev char.")
   ("toggle-option" . "Toggle a config option at runtime.\nFor example to toggle smart case search, use `:toggle search.smart-case`.")
   ("toggle_block_comments" . "Toggle block comments.")
   ("toggle_comments" . "Toggle comments.")
   ("toggle_line_comments" . "Toggle line comments.")
   ("transpose_view" . "Transpose view.")
   ("tree-sitter-highlight-name" . "Display name of tree-sitter highlight scope under the cursor.")
   ("tree-sitter-layers" . "Display language names of tree-sitter injection layers under the cursor.")
   ("tree-sitter-scopes" . "Display tree sitter scopes, primarily for theming and development.")
   ("tree-sitter-subtree" . "Display the smallest tree-sitter subtree that spans the primary selection, primarily for debugging queries.")
   ("trim_selections" . "Trim selections.")
   ("tutor" . "Open the tutorial.")
   ("undo" . "Undo last change.")
   ("unindent" . "Unindent selection.")
   ("update" . "Write changes only if the file has been modified.")
   ("vsplit" . "Open the file in a vertical split.")
   ("vsplit-new" . "Open a scratch buffer in a vertical split.")
   ("vsplit_new" . "Open a scratch buffer in a vertical split.")
   ("write" . "Write changes to disk. Accepts an optional path (:write some/path.txt)")
   ("write!" . "Force write changes to disk creating necessary subdirectories. Accepts an optional path (:write! some/path.txt)")
   ("write-all" . "Write changes from all buffers to disk.")
   ("write-all!" . "Forcefully write changes from all buffers to disk creating necessary subdirectories.")
   ("write-buffer-close" . "Write changes to disk and closes the buffer. Accepts an optional path (:write-buffer-close some/path.txt)")
   ("write-buffer-close!" . "Force write changes to disk creating necessary subdirectories and closes the buffer. Accepts an optional path (:write-buffer-close! some/path.txt)")
   ("write-quit" . "Write changes to disk and close the current view. Accepts an optional path (:wq some/path.txt)")
   ("write-quit!" . "Write changes to disk and close the current view forcefully. Accepts an optional path (:wq! some/path.txt)")
   ("write-quit-all" . "Write changes from all buffers to disk and close all views.")
   ("write-quit-all!" . "Forcefully write changes from all buffers to disk, creating necessary subdirectories, and close all views (ignoring unsaved changes).")
   ("x" . "Alias for :exit. Write changes to disk if the buffer is modified and then quit. Accepts an optional path (:exit some/path.txt).")
   ("x!" . "Alias for :exit!. Force write changes to disk, creating necessary subdirectories, if the buffer is modified and then quit. Accepts an optional path (:exit! some/path.txt).")
   ("xa" . "Alias for :write-quit-all. Write changes from all buffers to disk and close all views.")
   ("xa!" . "Alias for :write-quit-all!. Forcefully write changes from all buffers to disk, creating necessary subdirectories, and close all views (ignoring unsaved changes).")
   ("xit" . "Alias for :exit. Write changes to disk if the buffer is modified and then quit. Accepts an optional path (:exit some/path.txt).")
   ("xit!" . "Alias for :exit!. Force write changes to disk, creating necessary subdirectories, if the buffer is modified and then quit. Accepts an optional path (:exit! some/path.txt).")
   ("yank" . "Yank selection.")
   ("yank-diagnostic" . "Yank diagnostic(s) under primary cursor to register, or clipboard by default")
   ("yank-join" . "Yank joined selections. A separator can be provided as first argument. Default value is newline.")
   ("yank_joined" . "Yank joined.")
   ("yank_joined_to_clipboard" . "Yank joined to clipboard.")
   ("yank_joined_to_primary_clipboard" . "Yank joined to primary clipboard.")
   ("yank_main_selection_to_clipboard" . "Yank main selection to clipboard.")
   ("yank_main_selection_to_primary_clipboard" . "Yank main selection to primary clipboard.")
   ("yank_to_clipboard" . "Yank to clipboard.")
   ("yank_to_primary_clipboard" . "Yank to primary clipboard.")
   ("workspace_diagnostics_picker" . "Open workspace diagnostics picker.")
   ("workspace_symbol_picker" . "Open workspace symbol picker.")))
